### ISSUE TITLE
USB connection

### ISSUE THREAD

**Issue by raffaeler** [patrickhampson/Apcupsd.NET#2]
Is the protocol over USB/Modbus the same used by this library?

Thanks

**Comment by patrickhampson** [comment]
If APCUPSd is configured to use USB or ModBus the NIS protocol that this library uses should be the same.

**Comment by raffaeler** [comment]
Thanks @patrickhampson 
So basically I should write a new client that uses a modbus library to exchange the data and then let it be interpreted from the code in this library.
Do I understand correctly?

**Comment by patrickhampson** [comment]
http://www.apcupsd.org/manual/#modbus-driver

APCUPSd supports modbus out of the box already.  You should be able to configure it using the modbus driver and my library will interpret the NIS data that APCUPSd generates.

**Comment by raffaeler** [comment]
I got it working.
If I understood correctly, the NIS protocol never pushes events but I can only poll them via `GetEvents`.
Your `SubscribeToEventsFile()` can simulate real events, but it requires to run on the local machine to access the log file (which is a solution I don't like).

Could you please confirm that I did not misunderstand?
Thank you very much

**Comment by patrickhampson** [comment]
That is correct.  Sadly the SubscribeToEventsFile was the best solution given the available methods.  I plan to add a SubscribeToEventsPolling() method to poll the GetEvents NIS call and calculate which events are new.

**Comment by raffaeler** [comment]
Thank you. While reading more on the protocol, I discovered that I can't send command to the UPS to turn off/on.
I need that to "delay start" certain machines, therefore I have to drop APCUPSd and go with NUT instead.
Thanks for your time.
